# Generated by Django 3.2.8 on 2021-10-29 07:59

import account.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('avatar', models.ImageField(blank=True, upload_to=account.models.user_grouped_file_path)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('followers', models.ManyToManyField(blank=True, related_name='user_followers', to='account.Profile')),
                ('following', models.ManyToManyField(blank=True, related_name='user_following', to='account.Profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
